version: "3.4"

services:
  cartservice:
    image: ${DOCKER_REGISTRY-}cartservice
    ports:
      - "80"
    build:
      context: .
      dockerfile: CartService/Dockerfile

  dairyservice:
    image: ${DOCKER_REGISTRY-}dairyservice
    ports:
      - "80"
    build:
      context: .
      dockerfile: DairyService/Dockerfile
    networks:
      default:
        aliases:
          - dairy-service

  produceservice:
    image: ${DOCKER_REGISTRY-}produceservice
    ports:
      - "80"
    build:
      context: .
      dockerfile: ProduceService/Dockerfile
    networks:
      default:
        aliases:
          - produce-service

  notificationservice:
    image: ${DOCKER_REGISTRY-}notificationservice
    build:
      context: .
      dockerfile: NotificationService/Dockerfile


  deliveryservice:
    image: ${DOCKER_REGISTRY-}deliveryservice
    build:
      context: .
      dockerfile: DeliveryService/Dockerfile

