version: "3.4"

services:
  cartservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Logging__LogLevel__System.Net.Http.HttpClient=None
    ports:
      - "5099:80"

  dairyservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Logging__LogLevel__System.Net.Http.HttpClient=None
    ports:
      - "5230:80"

  produceservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Logging__LogLevel__System.Net.Http.HttpClient=None
    ports:
      - "5295:80"

  notificationservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Logging__LogLevel__System.Net.Http.HttpClient=None
    ports:
      - "5292:80"

  deliveryservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Logging__LogLevel__System.Net.Http.HttpClient=None
    ports:
      - "5290:80"
