version: "3.4"

services:
  cartservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5099:80"

  dairyservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  produceservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
